sudo: required
services:
  - docker

before_install:
  - docker build -t kkteng/dockr-react -f Dockerfile.dev .

script:
  - docker run -e CI=true kkteng/dockr-react npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeach-1"
  app: "dockr-react"
  env: "DockrReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-618300318837"
  bucket_path: "dockr-react"
  on:
    branch: master 
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
